### ISSUE TITLE
This app crashes on windows

### ISSUE THREAD

**Issue by dougforester** [spring-guides/gs-register-facebook-app#5]
I got a clone of this app from github. When i run it, it crashes with an exception. The console log is shown below. I have been reading about this problem online. It seems that it only works with gradle version 2.2, not 2.3 or 2.4. And it only works with Jackson version 2.2 or earlier. I'm trying to figure out how to configure the clone to use those packages/levels, but haven't a clue.
I just want to test my connection to facebook.
Here is the console log:
$ java -jar build/libs/gs-register-facebook-app-0.1.0.jar
09:54:31.791 [main] DEBUG o.s.web.client.RestTemplate - Created POST request for
 "https://graph.facebook.com/oauth/access_token"
09:54:31.797 [main] DEBUG o.s.web.client.RestTemplate - Setting request Accept h
eader to [application/x-www-form-urlencoded, multipart/form-data]
09:54:31.797 [main] DEBUG o.s.web.client.RestTemplate - Writing [{client_id=[164
5041485714181], client_secret=[05ce20ec304886a4c1fedc4356a2fcc9], grant_type=[cl
ient_credentials]}] using [org.springframework.social.facebook.connect.FacebookO
Auth2Template$1@1d5c71ff]
09:54:33.148 [main] DEBUG o.s.web.client.RestTemplate - POST request for "https:
//graph.facebook.com/oauth/access_token" resulted in 400 (Bad Request); invoking
 error handler
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.web.client.HttpClientErrorException: 400 Bad Requ
est
        at org.springframework.web.client.DefaultResponseErrorHandler.handleErro
r(DefaultResponseErrorHandler.java:91)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTempla
te.java:614)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.ja
va:570)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java
:530)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplat
e.java:330)
        at org.springframework.social.facebook.connect.FacebookOAuth2Template.po
stForAccessGrant(FacebookOAuth2Template.java:58)
        at org.springframework.social.oauth2.OAuth2Template.authenticateClient(O
Auth2Template.java:187)
        at org.springframework.social.oauth2.OAuth2Template.authenticateClient(O
Auth2Template.java:174)
        at hello.Application.fetchApplicationAccessToken(Application.java:34)
        at hello.Application.main(Application.java:16)

I would appreciate any help. Thanks.

**Comment by gregturn** [comment]
@dougforester Can you recheck now that the app has been updated?

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
